brew install --cask 1password
brew install --cask alfred
brew install --cask bartender
brew install --cask bettertouchtool
brew install --cask beyond-compare
brew install --cask firefox
brew install --cask google-chrome
brew install --cask iterm2
brew install --cask keyboard-maestro
brew install --cask pdf-expert
brew install --cask postico
brew install --cask slack
brew install --cask visual-studio-code
brew install --cask discord