brew cask install hyperswitch
brew cask install dash
brew cask install bartender
brew cask install keyboard-maestro
brew cask install google-chrome
brew cask install istat-menus
brew cask install beyond-compare
brew cask install sublime-text
brew cask install dash
brew cask install alfred
brew cask install nvalt
brew cask install bettertouchtool
brew cask install macdown
brew cask install wavebox