brew install --cask bartender
brew install --cask keyboard-maestro
brew install --cask google-chrome
brew install --cask istat-menus
brew install --cask beyond-compare
brew install --cask alfred
brew install --cask bettertouchtool
brew install --cask firefox
brew install --cask visual-studio-code
brew install --cask dash